sigb/sigb/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('user/', include('user.urls')),
    path('', include('core.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

sigb/core/models.py
from django.db import models


class Bolsista(models.Model):

    nome = models.CharField(max_length=255)
    cpf = models.CharField(max_length=11, unique=True)
    dt_nascimento = models.DateField()
    nome_mae = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    pis_pasep = models.CharField()
    conta_bancaria = models.CharField(max_length=255)
    cep = models.CharField(max_length=8)
    logradouro = models.CharField(max_length=255)
    numero = models.IntegerField()
    cidade = models.CharField(max_length=255)
    uf = models.CharField(max_length=2)
    documentacao = models.FileField(upload_to='bolsista_documentacao')

    def __str__(self):
        return f'{self.nome} - {self.cpf}'


class Edital(models.Model):

    numero = models.IntegerField()
    vigencia = models.DateField()
    descricao = models.CharField(max_length=255)

    def __str__(self):
        return str(self.numero)


class Bolsa(models.Model):

    modalidade = models.CharField(max_length=255)
    carga_horaria = models.IntegerField()
    valor = models.FloatField()

    def __str__(self):
        return str(self.modalidade)


class RelacaoBolistaBolsa(models.Model):

    bolsista = models.ForeignKey(Bolsista, on_delete=models.CASCADE)
    edital = models.ForeignKey(Edital, on_delete=models.CASCADE)
    bolsa = models.ForeignKey(Bolsa, null=True, blank=True, on_delete=models.CASCADE)

    funcao = models.CharField(max_length=255)
    situacao = models.CharField(max_length=255)
    dt_desligamento = models.DateField()

    # Outorga
    vigencia_outorga = models.DateField()
    data_outorga = models.DateField()
    termo_outorga = models.FileField(null=True, blank=True, upload_to='termo_outorga')

sigb/core/models/bolsa.py
from django.db import models

from .bolsista import Bolsista
from .edital import Edital


__all__ = [
    'Bolsa'
]


class Bolsa(models.Model):
    modalidade = models.CharField(max_length=255)
    funcao = models.CharField(max_length=255)
    carga_horaria = models.IntegerField()
    valor = models.FloatField()
    situacao = models.CharField(max_length=255)
    dt_desligamento = models.DateField(null=True, blank=True)
    vigencia_outorga = models.DateField()
    data_outorga = models.DateField()
    termo_outorga = models.FileField(null=True, blank=True, upload_to='termo_outorga')
    bolsista = models.ForeignKey(Bolsista, on_delete=models.CASCADE)
    edital = models.ForeignKey(Edital, on_delete=models.CASCADE)

    class Meta:
        ordering = ['situacao']

    def __str__(self):
        return self.modalidade

sigb/core/models/bolsista.py
from django.db import models


__all__ = [
    'Bolsista',
]


class Bolsista(models.Model):
    nome = models.CharField(max_length=255)
    cpf = models.CharField(max_length=11, unique=True)
    dt_nascimento = models.DateField()
    nome_mae = models.CharField(max_length=255)
    email = models.EmailField(unique=True)
    pis_pasep = models.CharField()
    conta_bancaria = models.CharField(max_length=255)
    cep = models.CharField(max_length=8)
    logradouro = models.CharField(max_length=255)
    numero = models.IntegerField()
    cidade = models.CharField(max_length=255)
    uf = models.CharField(max_length=2)
    documentacao = models.FileField(null=True, blank=True, upload_to='bolsista_documentacao')

    class Meta:
        ordering = ['nome', 'cpf']

    def __str__(self):
        return self.cpf

sigb/core/models/edital.py
from django.db import models

from .bolsista import Bolsista


__all__ = [
    'Edital',
]


class Edital(models.Model):
    projeto = models.CharField(max_length=255)
    numero = models.IntegerField()
    nucleo_responsavel = models.CharField(max_length=255)
    vigencia = models.DateField()
    bolsistas = models.ManyToManyField(Bolsista)

    class Meta:
        ordering = ['projeto', 'numero']

    def __str__(self):
        return self.projeto

sigb/core/forms/bolsa.py
from django import forms
from django.contrib.admin.options import widgets


from ..models.bolsa import Bolsa
from ..models.edital import Edital


class BolsaAdminForm(forms.ModelForm):
    SITUACAO_BOLSISTA = (
        ('', 'Selecionar'),
        ('Ativo', 'Ativo'),
        ('Afastado', 'Afastado'),
        ('Desistente', 'Desistente'),
        ('Desligado', 'Desligado'),
        ('Bolsa Concluída', 'Bolsa Concluída'),
    )

    situacao = forms.ChoiceField(
        label='Situação',
        choices=SITUACAO_BOLSISTA
    )

    class Meta:
        model = Bolsa
        exclude = [ 'bolsista' ]

        labels = {
            'modalidade': 'Modalidade',
            'funcao': 'Função',
            'carga_horaria': 'Carga horária',
            'valor': 'Valor',
            'dt_desligamento': 'Data de desligamento',
            'vigencia_outorga': 'Vigência da outorgação',
            'data_outorga': 'Data de outorgação',
            'termo_outorga': 'Termo de outorga'
        }


class BolsaForm(BolsaAdminForm):
    situacao = forms.ChoiceField(
        label='Situação',
        choices=BolsaAdminForm.SITUACAO_BOLSISTA,
        widget=forms.Select(attrs={ 'class': 'form-select' })
    )
    edital = forms.ModelChoiceField(
        queryset=Edital.objects.all(),
        widget=forms.Select(attrs={ 'class': 'form-select' })
    )

    class Meta(BolsaAdminForm.Meta):
        widgets = {
            'modalidade': forms.TextInput(attrs={ 'class': 'form-control' }),
            'funcao': forms.TextInput(attrs={ 'class': 'form-control' }),
            'carga_horaria': forms.TextInput(attrs={ 'class': 'form-control' }),
            'valor': forms.NumberInput(attrs={ 'class': 'form-control' }),
            'dt_desligamento': forms.DateInput(attrs={ 'class': 'form-control', 'type': 'date' }),
            'vigencia_outorga': forms.DateInput(attrs={ 'class': 'form-control', 'type': 'date' }),
            'data_outorga': forms.DateInput(attrs={ 'class': 'form-control', 'type': 'date' }),
            'termo_outorga': forms.FileInput(attrs={'class': 'form-control'})
        }

sigb/core/forms/bolsista.py
from datetime import date

from django import forms

from ..models.bolsista import Bolsista


__all__ = [
    'BolsistaForm',
    'BolsistaAdminForm',
]


class BolsistaAdminForm(forms.ModelForm):
    class Meta:
        model = Bolsista
        fields = '__all__'

        labels = {
            'nome': 'Nome',
            'cpf': 'CPF',
            'dt_nascimento': 'Data de Nascimento',
            'nome_mae': 'Nome da mãe',
            'email': 'E-mail',
            'pis_pasep': 'PIS/PASEP',
            'conta_bancaria': 'Conta Bancária',
            'cep': 'CEP',
            'logradouro': 'Logradouro',
            'numero': 'Número',
            'cidade': 'Cidade',
            'uf': 'UF',
            'documentacao': 'Documentação',
        }


class BolsistaForm(BolsistaAdminForm):
    class Meta(BolsistaAdminForm.Meta):
        widgets = {
            'nome': forms.TextInput(attrs={'class': 'form-control'}),
            'cpf': forms.TextInput(attrs={'class': 'form-control'}),
            'dt_nascimento': forms.DateInput(attrs={
                'class': 'form-control',
                'type': 'date',
                'max': date.today().isoformat()
            }),
            'nome_mae': forms.TextInput(attrs={'class': 'form-control'}),
            'email': forms.EmailInput(attrs={'class': 'form-control'}),
            'pis_pasep': forms.TextInput(attrs={'class': 'form-control'}),
            'conta_bancaria': forms.TextInput(attrs={'class': 'form-control'}),
            'cep': forms.TextInput(attrs={'class': 'form-control'}),
            'logradouro': forms.TextInput(attrs={'class': 'form-control'}),
            'numero': forms.NumberInput(attrs={'class': 'form-control'}),
            'cidade': forms.TextInput(attrs={'class': 'form-control'}),
            'uf': forms.TextInput(attrs={'class': 'form-control'}),
            'documentacao': forms.FileInput(attrs={'class': 'form-control'}),
        }

sigb/core/forms/edital.py
from django import forms

from ..models.edital import Edital


__all__ = [
    'EditalAdminForm',
    'EditalForm',
    'EditalVincularBolsistaForm'
]


class EditalAdminForm(forms.ModelForm):
    class Meta:
        model = Edital
        exclude = [ 'bolsistas', ]

        labels = {
            'projeto': 'Projeto',
            'numero': 'Número',
            'nucleo_responsavel': 'Núcleo Responsável',
            'vigencia': 'Vigência',
        }


class EditalForm(EditalAdminForm):
    class Meta(EditalAdminForm.Meta):
        widgets = {
            'projeto': forms.TextInput(attrs={ 'class': 'form-control' }),
            'numero': forms.NumberInput(attrs={ 'class': 'form-control' }),
            'nucleo_responsavel': forms.TextInput(attrs={ 'class': 'form-control' }),
            'vigencia': forms.DateInput(attrs={ 'class': 'form-control', 'type': 'date' }),
        }


class EditalVincularBolsistaForm(forms.Form):
    edital = forms.ModelChoiceField(
        queryset=Edital.objects.all(),
        widget=forms.Select(attrs={ 'class': 'form-select' })
    )

sigb/core/views/bolsa.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import redirect, render
from django.views import View
from django.views.generic import CreateView, UpdateView

from ..forms.bolsa import BolsaForm
from ..models.bolsa import Bolsa
from ..models.bolsista import Bolsista


__all__ = [
    'BolsaCreate',
    'BolsaUpdate',
]


class BolsaCreate(LoginRequiredMixin, View):
    template_name =  'core/bolsa_form.html'

    def get(self, request, bolsista_id):
        form = BolsaForm()
        bolsista = Bolsista.objects.get(pk=bolsista_id)
        form.fields['edital'].queryset = bolsista.edital_set.all()

        return render(request, self.template_name, { 'form': form })

    def post(self, request, bolsista_id):
        form = BolsaForm(request.POST)

        if form.is_valid():
            form.instance.bolsista_id = bolsista_id
            form.save()
            return redirect('bolsista_detail', pk=bolsista_id)

        return render(request, self.template_name, { 'form': form })


class BolsaUpdate(LoginRequiredMixin, View):
    template_name =  'core/bolsa_form.html'

    def get(self, request, pk):
        bolsa = Bolsa.objects.get(pk=pk)
        form = BolsaForm(instance=bolsa)
        bolsista = Bolsista.objects.get(pk=bolsa.bolsista_id)
        form.fields['edital'].queryset = bolsista.edital_set.all()

        return render(request, self.template_name, { 'form': form })

    def post(self, request, pk):
        bolsa = Bolsa.objects.get(pk=pk)
        form = BolsaForm(request.POST, instance=bolsa)

        if form.is_valid():
            form.save()
            return redirect('bolsista_detail', pk=bolsa.bolsista_id)

        return render(request, self.template_name, { 'form': form })

sigb/core/views/bolsista.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import CreateView, ListView, UpdateView, DetailView
from django.urls import reverse


from .utils import DownloadView
from ..forms.bolsista import BolsistaForm
from ..models.bolsista import Bolsista


__all__ = [
    'BolsistaList',
    'BolsistaDetailView',
    'BolsistaCreate',
    'BolsistaUpdate',
    'BolsistaDownload',
    # 'DeclaracaoVinculoView',
]


class BolsistaList(LoginRequiredMixin, ListView):
    model = Bolsista
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get(self.page_kwarg) or 1
        page_range = context['paginator'].get_elided_page_range(
            number=page, on_each_side=2, on_ends=1
        )
        context.update({ 'page_range': page_range })

        return context


class BolsistaDetailView(LoginRequiredMixin, DetailView):
    model = Bolsista

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)

        return context


class BolsistaCreate(LoginRequiredMixin, CreateView):
    model = Bolsista
    form_class = BolsistaForm

    def get_success_url(self):
        return reverse('bolsista_detail', kwargs={ 'pk': self.object.id })


class BolsistaUpdate(LoginRequiredMixin, UpdateView):
    model = Bolsista
    form_class = BolsistaForm
    template_name_suffix = '_update_form'

    def get_object(self):
        obj = super().get_object()
        obj.dt_nascimento = obj.dt_nascimento.strftime('%Y-%m-%d')
        return obj

    def get_success_url(self):
        return reverse('bolsista_detail', kwargs={ 'pk': self.object.id })


class BolsistaDownload(LoginRequiredMixin, DownloadView):
    model = Bolsista


# class DeclaracaoVinculoView(LoginRequiredMixin, View):
#     def get(self, _, vinculo_id):
#         vinculo = BolsistaBolsa.objects.get(id=int(vinculo_id))
#
#         buffer = BytesIO()
#         pdf = canvas.Canvas(buffer)
#         pdf.drawString(250, 250, 'DECLARAÇÃO')
#         pdf.drawString(100, 750, '''
#         Declaro para todos devidos fins, que {nome}, inscrito no CPF n° {cpf},
#         é bolsista do Edital {edital} e exerce a atividade de {{atividade}},
#         vinculado ao Projeto {{projeto}}, desenvolvido pela Escola de Saúde Pública
#         da Paraíba - ESP/PB, entre {data_outorga} até o presente momento
#         '''.format(
#             nome=vinculo.bolsista.nome,
#             cpf=vinculo.bolsista.cpf,
#             edital=vinculo.edital,
#             data_outorga=vinculo.data_outorga
#         ))
#
#         pdf.showPage()
#         pdf.save()
#
#         buffer.seek(0)
#         return FileResponse(buffer, as_attachment=True, filename='declaracao.pdf')

sigb/core/views/edital.py
from django.contrib.auth.mixins import LoginRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView, ListView, UpdateView, View

from ..forms.edital import EditalForm, EditalVincularBolsistaForm
from ..models.bolsista import Bolsista
from ..models.edital import Edital


__all__ = [
    'EditalList',
    'EditalCreate',
    'EditalUpdate',
    'EditalVincularBolsistaView',
]


class EditalList(LoginRequiredMixin, ListView):
    model = Edital
    paginate_by = 25

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        page = self.request.GET.get(self.page_kwarg) or 1
        page_range = context['paginator'].get_elided_page_range(
            number=page, on_each_side=2, on_ends=1
        )
        context.update({ 'page_range': page_range })

        return context


class EditalCreate(LoginRequiredMixin, CreateView):
    model = Edital
    form_class = EditalForm
    success_url = reverse_lazy('edital_list')


class EditalUpdate(LoginRequiredMixin, UpdateView):
    model = Edital
    form_class = EditalForm
    success_url = reverse_lazy('edital_list')
    template_name_suffix = '_update_form'


class EditalVincularBolsistaView(LoginRequiredMixin, View):
    template_name = 'core/edital_vincular_bolsista_form.html'

    def get(self, request, **_):
        form = EditalVincularBolsistaForm()
        return render(request, self.template_name, { 'form': form })

    def post(self, request, bolsista_id):
        form = EditalVincularBolsistaForm(request.POST)

        if form.is_valid():
            bolsista = Bolsista.objects.get(pk=bolsista_id)
            edital = form.cleaned_data['edital']
            edital.bolsistas.add(bolsista)

        return self.get(request)

sigb/core/views/utils.py
import csv

from django.db import models
from django.http import StreamingHttpResponse
from django.views.generic import View


class DownloadView(View):
    model: models.Model

    @classmethod
    def csv_gerador(cls, writer, queryset):
        field_names = [
            field.name 
            for field 
            in cls.model._meta.fields
        ]
        yield writer.writerow(field_names)

        for obj in queryset.iterator():
            yield writer.writerow([
                getattr(obj, field) for field in field_names
            ])

    def get(self, _):
        queryset = self.model.objects.all()
        buffer = self.Echo()
        writer = csv.writer(buffer)
        return StreamingHttpResponse(
            self.csv_gerador(writer, queryset),
            content_type='text/csv',
            headers={
                "Content-Disposition": 'attachment; filename="bolsistas_exportacao.csv"'
            }
        )

    class Echo:
        def write(self, value):
            return value

sigb/templates/core/bolsa_form.html
{% extends 'base.html' %}

{% block main %}
<div class="container-xl h-100 mt-4">
  <h2>Adicionar Bolsa</h2>
  <hr>
  {% include 'form.html' %} 
</div>
{% endblock main %}

sigb/templates/core/bolsa_list.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
<div class="container-xl h-100">
  <form method="GET" class="container-xl my-2">
    <div class="row">
      <div class="col-lg ps-0 fw-semibold mt-3">
        {{ object_list.count }} resultados
      </div>
      <div class="col-lg mt-3 pe-0 d-flex justify-content-end">
        <div class="me-1">
          <a href="{% url 'bolsa_create' %}" class="btn btn-primary">
            <i class="bi bi-plus-circle"></i> Adicionar
          </a>
        </div>
      </div>
    </div>
  </form>
  <div class="table-responsive-xl mt-3">
    <table class="table align-middle">
      <thead>
        <th class="col-4">MODALIDADE</th> 
        <th class="col-3">CARGA HORÁRIA</th>
        <th class="col-4">VALOR</th>
        <th class="col-1">AÇÕES</th>
      </thead> 
      <tbody>
        {% for bolsa in object_list %}
        <tr>
          <td class="col-7">{{ bolsa.modalidade }}</td>
          <td class="col-4">{{ bolsa.carga_horaria }}</td>
          <td class="col-4">{{ bolsa.valor }}</td>
          <td class="col-1">
            <a href="{% url 'bolsa_update' pk=bolsa.id %}" class="btn btn-warning">
              <i class="bi bi-pencil-fill" ></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>  
  </div>
  {% if paginator.num_pages > 1 %}
  <nav class="mt-4" aria-label="...">
    <ul class="pagination pagination-sm justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <button
          type="button"
          onclick="toPage('{{ page_obj.previous_page_number }}')"
          class="page-link"
        ><</button>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link"><</a>
      </li>
      {% endif %}
      {% for numero_pagina in page_range %}
        {% if numero_pagina == paginator.ELLIPSIS %}
          <li class="page-item disabled">
            <a href="#" class="page-link">{{ numero_pagina }}</a>
          </li>
        {% else %}
          <li class="page-item {% if numero_pagina == page_obj.number %}active{% endif %}">
            <button
              type="button"
              onclick="toPage('{{ numero_pagina }}')"
              class="page-link"
            >
              {{ numero_pagina }} {{ paginator.number }}
            </button>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item">
        <button
          type="button"
          onclick="toPage('{{ page_obj.next_page_number }}')"
          class="page-link"
        >></button>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link">></a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock main %}

sigb/templates/core/bolsista_detail.html
{% extends 'base.html' %}

{% load utils %}

{% block main %}
<div class="container-xl h-100 mt-4">
  <h1>{{ bolsista.nome }}</h1>
  <hr>
  <div class="row">
    <div class="col-lg-4">
      <p><b>CPF:</b> {{ bolsista.cpf }}</p>
    </div>
    <div class="col-lg-4">
      <p><b>Data de nascimento:</b> {{ bolsista.dt_nascimento }}</p>
    </div>
    <div class="col-lg-4">
      <p><b>E-mail:</b> {{ bolsista.email }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <p><b>PIS/PASEP:</b> {{ bolsista.pis_pasep }}</p>
    </div>
    <div class="col-lg-4">
      <p><b>Nome da mãe</b> {{ bolsista.nome_mae }}</p> 
    </div>
    <div class="col-lg-4">
      <p><b>Dados Bancários:</b> {{ bolsista.conta_bancaria }}</p>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-4">
      <p><b>CEP:</b> {{ bolsista.cep }}</p>
    </div>
    <div class="col-lg-8">
      <p><b>Logradouro:</b> {{ bolsista.logradouro }}</p>
    </div>
  </div>
  <div class="row">
    <div class="col-lg-4">
      <p><b>Número:</b> {{ bolsista.numero }}</p>
    </div>
    <div class="col-lg-4">
      <p><b>Cidade:</b> {{ bolsista.cidade }}</p>
    </div>
    <div class="col-lg-4">
      <p><b>UF:</b> {{ bolsista.uf }}</p>
    </div>
  </div>
  <div class="row mt-3">
    <div class="col-lg-4">
      <p><b>Documentação:</b>
        <a href="{{ bolsista.documentacao.url }}" download>
          {{ bolsista.documentacao.name|get_filename }}
        </a>
      </p>
    </div>
  </div>

  <div class="row justify-content-md-center my-4">
    <div class="col col-xl-3 d-grid">
      <div class="d-grid">
        <a href="{% url 'bolsista_update' pk=bolsista.id %}" class="btn btn-primary">Editar</a>
      </div>
    </div>
  </div>

  <h2 class="h3 mt-5">Bolsas</h2>
  <div class="table-responsive mt-4">
    <table class="table align-middle">
      <thead>
        <th>MODALIDADE</th> 
        <th>FUNÇÃO</th>
        <th>CARGA HORÁRIRA</th>
        <th>VALOR</th>
        <th>EDITAL</th>
        <th>SITUAÇÃO</th>
        <th>AÇÕES</th>
      </thead>
      <tbody>
        {% for bolsa in bolsista.bolsa_set.all %}
        <tr>
          <td>{{ bolsa.modalidade }}</td>
          <td>{{ bolsa.funcao }}</td>
          <td>{{ bolsa.carga_horaria }}</td>
          <td>{{ bolsa.valor }}</td>
          <td>{{ bolsa.edital }}</td>
          <td>{{ bolsa.situacao }}</td>
          <td>
            <a href="{% url 'bolsa_update' pk=bolsa.id %}" class="btn btn-warning">
              <i class="bi bi-pencil-fill" ></i>
            </a>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="row justify-content-md-center my-4">
    <div class="col col-xl-3 d-grid">
      <div class="d-grid">
        <a href="{% url 'bolsa_create' bolsista_id=bolsista.id %}" class="btn btn-primary">Adicionar Bolsa</a>
      </div>
    </div>
  </div>

  <h2 class="h3 mt-5">Editais</h2>
  <div class="table-responsive mt-4">
    <table class="table align-middle">
      <thead>
        <th>PROJETO</th> 
        <th>NUMERO</th>
        <th>NÚCLEO RESPONSÁVEL</th>
      </thead>
      <tbody>
        {% for edital in bolsista.edital_set.all %}
        <tr>
          <td>{{ edital.projeto }}</td>
          <td>{{ edital.numero }}</td>
          <td>{{ edital.nucleo_responsavel }}</td>
        </tr>
        {% endfor %}
      </tbody>
    </table>
  </div>

  <div class="row justify-content-md-center my-4">
    <div class="col col-xl-3 d-grid">
      <div class="d-grid">
        <a href="{% url 'edital_vincular_bolsista' bolsista_id=bolsista.id %}" class="btn btn-primary">Vincular Edital</a>
      </div>
    </div>
  </div>
</div>
{% endblock main %}

sigb/templates/core/bolsista_form.html
{% extends 'base.html' %}

{% block main %}
<div class="container-xl h-100 mt-4">
  <h1>{% block form_title %}Adicionar Bolsista{% endblock form_title %}</h1>
  <hr>
  {% include 'form.html' %} 
</div>
{% endblock main %}

sigb/templates/core/bolsista_list.html
{% extends 'base.html' %}

{% load static %}

{% block main %}
<div class="container-xl h-100">
  <form method="GET" class="container-xl my-2">
    <div class="row">
      <div class="col-lg ps-0 fw-semibold mt-3">
        {{ object_list.count }} resultados
      </div>
      <div class="col-lg mt-3 pe-0 d-flex justify-content-end">
        <div class="me-1">
          <a href="{% url 'bolsista_create' %}" class="btn btn-success">
            <i class="bi bi-plus-circle"></i> Adicionar
          </a>
        </div>
        <div>
          <a href="{% url 'bolsista_download' %}" class="btn btn-secondary">
            <i class="bi bi-download"></i> Baixar
          </a>
        </div>
      </div>
    </div>
  </form>
  <div class="table-responsive-xl mt-3">
    <table class="table align-middle">
      <thead>
        <th class="col-7">NOME</th> 
        <th class="col-4">CPF</th>
        <th class="col-1">AÇÕES</th>
      </thead> 
      <tbody>
        {% for bolsista in object_list %}
        <tr>
          <td class="col-7">{{ bolsista.nome }}</td>
          <td class="col-4">{{ bolsista.cpf }}</td>
          <td class="col-1">
            <div class="d-flex flex-row-reverse">
              <a href="{% url 'bolsista_detail' pk=bolsista.id %}" class="btn btn-primary">
                <i class="bi bi-eye-fill" ></i>
              </a>
            </div>
          </td>
        </tr>
        {% endfor %}
      </tbody>
    </table>  
  </div>
  {% if paginator.num_pages > 1 %}
  <nav class="mt-4" aria-label="...">
    <ul class="pagination pagination-sm justify-content-center">
      {% if page_obj.has_previous %}
      <li class="page-item">
        <button
          type="button"
          onclick="toPage('{{ page_obj.previous_page_number }}')"
          class="page-link"
        ><</button>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link"><</a>
      </li>
      {% endif %}
      {% for numero_pagina in page_range %}
        {% if numero_pagina == paginator.ELLIPSIS %}
          <li class="page-item disabled">
            <a href="#" class="page-link">{{ numero_pagina }}</a>
          </li>
        {% else %}
          <li class="page-item {% if numero_pagina == page_obj.number %}active{% endif %}">
            <button
              type="button"
              onclick="toPage('{{ numero_pagina }}')"
              class="page-link"
            >
              {{ numero_pagina }} {{ paginator.number }}
            </button>
          </li>
        {% endif %}
      {% endfor %}
      {% if page_obj.has_next %}
      <li class="page-item">
        <button
          type="button"
          onclick="toPage('{{ page_obj.next_page_number }}')"
          class="page-link"
        >></button>
      </li>
      {% else %}
      <li class="page-item disabled">
        <a href="#" class="page-link">></a>
      </li>
      {% endif %}
    </ul>
  </nav>
  {% endif %}
</div>
{% endblock main %}

sigb/templates/core/bolsista_update_form.html
{% extends 'core/bolsista_form.html' %}

{% block form_title %}Atualizar Bolsista{% endblock form_title %}